
Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Customer
    username: root
    password: kali

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  main:
    web-application-type: servlet